### ISSUE TITLE
Замечания по работе

### ISSUE THREAD

**Issue by AndriiLitvin** [maxhasl/maxhasl.github.io#1]
Визуально: http://joxi.ru/5mdMgP7ibP9G21

Код:
1) Классы должны быть говорящие, чтоб без контента можно было понять что туда выводить.
2) Верстка не резиновая а фиксированная. Размеры в "px". при скроле экрана делается такое http://joxi.ru/J2blgP1FdBp7r6 http://joxi.ru/vAWZzP3sJaW12W

**Comment by maxhasl** [comment]
Исправил

**Comment by AndriiLitvin** [comment]
1) Выровнять по центру при помощи margin, чтоб при ресайзе окна он всегда был по центру
2) Отступы не соответствуют макету https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png
3)box-shadow слишком велик уменьш его в 6 раз)
4) тут http://joxi.ru/GrqgjnLtXlzR2z отступы. смотри макет выше

**Comment by maxhasl** [comment]
Updated

**Comment by AndriiLitvin** [comment]
Зачет

**Comment by maxhasl** [comment]
Спасибо, Андрей)
