### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [maxhasl/maxhasl.github.io#21]
1.  сборка самого проекта не совсем правильно сделана. читай тут как https://habrahabr.ru/post/250569/ где у src у тебя лежат файлы с которыми ты работаешь а в build готовый проэкт.

2.
![image](https://cloud.githubusercontent.com/assets/13675947/13985250/537ffdfc-f104-11e5-8764-34ca916e0d51.png)
тут его не должно быть

3.
![image](https://cloud.githubusercontent.com/assets/13675947/13985284/8c875e24-f104-11e5-8afc-8d160394fa12.png)

если пишешь scss топиши так 

```
.clearfix{
  *zoom: 1;
  &:before{
    content: '';
    display: table;
  }
  &:after{
    content: '';
    display: table;
    clear: both;
  }
}
```

http://dedushka.org/uroki/6672.html/, http://www.sassmeister.com/
переделай все

4,
не хватает метатега для отображения на мобильном http://frontender.com.ua/mobile-web/wtf-viewport/

5,
все внешние скрипты скачиваешь конкатынируешь минифицируешь и подключаешь vendor.min.js

6.
и вот тож можешь пофиксить https://validator.w3.org/nu/?doc=http%3A%2F%2Fmaxhasl.github.io%2FGoIT%2Fjavascript%2FEXAM%2Findex.html

**Comment by maxhasl** [comment]
Обновил. Андрей хелп!! ie8 шрифты подключает через раз, я хз что делать с ними уже(((
в eot перевел, уже отдельно переменные для них ввел и подключал по-очереди типа 
font-family: $montBold, $montBold-ie8; 
нифига, то подгружает то нет, рандом((
а так поддержку ie8 сделал, все круглое, только карусели квадратные остались ибо на градиент поверх картинок чет border-radius не пашет(

**Comment by maxhasl** [comment]
проблема решилась только с помощью google fonts(

**Comment by AndriiLitvin** [comment]
1, сделай чтоб на плитке при клике на  картинку она открывалась в модальном окне.
2, сделай кнопкам какой то ховер
3, пофиксь шрифты что то они не пашут на ие
вообще вот такой наборчик должен быть при подключении.

```
@font-face {
    font-family: 'Montserrat-Regular';
    src: url('../fonts/Montserrat-Regular.ttf') format('truetype');
    src: url('../fonts/Montserrat-Regular.eot');
    src: url('../fonts/Montserrat-Regular.woff') format('woff'),
         url('../fonts/Montserrat-Regular.ttf') format('truetype'),
         url('../fonts/Montserrat-Regular.svg') format('svg');
}

```

вот ссылка где можно форматнуть шрифт http://www.font2web.com/
если не поможет добавь sans-serif
4, тут 
![image](https://cloud.githubusercontent.com/assets/13675947/14138896/58c9feb0-f678-11e5-83ab-719abc368d7c.png)
нет ссылок

**Comment by maxhasl** [comment]
обновил! в ие8 модалька -- gracefull degradation))

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
только 
![image](https://cloud.githubusercontent.com/assets/13675947/14228741/7877cdc6-f927-11e5-880a-392d1c67d1ac.png)
это должно быть в корне exam
