### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [maxhasl/maxhasl.github.io#4]
< div class="top_menu">
     < ul>
        < div class="first_part_menu">
           < li><a href="#">Meu YouBike</a>< /li>
        < /div>
        < div class="last_part_menu" >
         < li >< a href="#">< img src="img/flag.png" alt="">Minhas Ofertas< /a>< /li>
        < /div >
     < /ul>
< /div>
такую структуру ненужно делать если тебе нужно две менюшки делаешь 2 ul
< button class="button">< a href="#">Create my account< /a>< /button>-тут все в button можно сделать а лучше использовать input type="submit" - так как нужно сабмитить форму. хотя это не принципиально  это тоже все решается

http://joxi.ru/xAe0gQ1sWaBK2y
1)Всерстать а не картинкой
2)менюшка улетает влево при большом экране. убери маргин и реши этот вопрос по другому. можно сделать контейнер задать ему ширину выровнять по центу и весь контент кинуть во внутрь и сделать им флоат 
3)стрелочку сделай через спец символы либо картинкой

**Comment by maxhasl** [comment]
updated

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
