### ISSUE TITLE
Замечания по работе 5.2 table

### ISSUE THREAD

**Issue by AndriiLitvin** [maxhasl/maxhasl.github.io#5]
< td class="not_display_cell">NONE< /td> - это костыль и это не очень хорошо
http://joxi.ru/82Q5BPYSPqWQ2d -бордеры убери

**Comment by maxhasl** [comment]
Андрей, как тогда сделать чтоб пустые строки и столбцы не схлопывались, не задавая им ширину и высоту и соблюдая задание "сверстать все только через rowspan и colspan" ? гуглил способы , ничего не нашел, только или задавать высоту ширину или делать такой каркас как использовал

**Comment by AndriiLitvin** [comment]
либо таблице задаешь высоту и ширину, либо всем tr высоту одинаковою и все. а остальное через 
через rowspan и colspan

**Comment by maxhasl** [comment]
updated

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
