### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [maxhasl/maxhasl.github.io#7]
так у тебя не совсем правильно стоит условие 
Экран 320-479(макет 320)
Экран 480-767(макет 480)
Экран 768-959(макет768)
Экран 960(макет 960)
## на экранах свыше 960рх http://joxi.ru/Y2L0zPXsnMM862

1)отцентрируй
2)3)бордеры должны быть на весь экран.
## Экран 960 http://joxi.ru/823pdlkF6aaMXA

1) нет ховера. 

и поправишь условия потом перепроверю так как не могу проверить правельность верстки
для мобильной верстки можешь использовать вот этот плагин в хроме https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc

**Comment by maxhasl** [comment]
updated

**Comment by AndriiLitvin** [comment]
+везде есть одинаковый контейнер
+везде text-shadow

## Экран 960 http://joxi.ru/v29l3qWFGR0Y6m мозила

1) там просто навигация можно сделать просто лишками можешь глянуть карусель в будстрапе
ну если уже так то там поменяй id а то если срабатывает первый авыключается второй. и подровняй

## Экран 768 http://joxi.ru/KAgGg68tgN1XBA

1) отступы либо контейнер
2) Отступы должны быть одинаковые
3)Контент шире
4)левее
5) отступы больше
6)box-shadow: 0px 1px 2px 0.00px rgba(0, 0, 0, 0.05);
7)внутри паддинги больше
8) text-shadow
9) на уровне с контентом выше
10) бордер тоньше
11)там тоже бордер
12) отступы разные
13)все должно быть на одном уровне

## Экран 480 http://joxi.ru/1A5pK7zFKzBvv2

1) отцентрировать
2) когда появляется меню идет смещение влево
3) тут шире смотри макет
4) отступы разные
5) на всю ширину
6) по центру
7) на всю ширину
8)9) по всему макету отступы меньше
10) все в одну строчку

## Экран 320 

![image](https://cloud.githubusercontent.com/assets/13675947/12233396/9c0760a6-b86f-11e5-9f10-ae1ff59b97d4.png)

Не соответствует макету))

для мобильной верстки можешь использовать вот этот плагин https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc

**Comment by maxhasl** [comment]
UPDATED

**Comment by AndriiLitvin** [comment]
## http://joxi.ru/n2Y5gPkSjR6e82

1) подровнять
2) убрать
+тоже самое и на верхнем слайде http://joxi.ru/EA4vLykFDKNvlm 
и это делать через css

## Экран 768 http://joxi.ru/RmzkEJqFWdNDa2
- сделай чтоб каждый блок не выходил за линию. то есть сделай везде одинаковый контейнер

## Экран 480 http://joxi.ru/n2Y5gPkSjR6lW2

1)Блок шире
2)Отступ больше
3) Отступ  меньше , и вообще отцентрируй все. можно сделать не флоатами а display: inline-block;

**Comment by maxhasl** [comment]
Обновил.
Андрей, хелпани! точки в пагинациях, в активном состоянии, на компе во всех браузерах нормально отображаются. Смотрю на мобиле через Chrome/Mozzila  - они мелкие, как будто font-size не задан. В чем проблема?

**Comment by AndriiLitvin** [comment]
почему ты так не сделаешь? я же писал что через css

<pre>.page {
    display: inline-block;
    width: 16px;
    height: 16px;
    margin-left: 5px;
    background-color: rgba(0, 0, 0, 0.2);
    border-radius: 10px;
    text-decoration: none;
    position: relative;
}
.checked {
    display: block;
    opacity: 0;
    text-align: center;
    background: #fff;
    height: 8px;
    width: 8px;
    border-radius: 50%;
    position: absolute;
    top: 4px;
    left: 4px;
}</pre>
убери эти точки. так никто не делает. на старых ie будут квадратики ну и пох. Все равно поддержки уже для старых нет (http://korrespondent.net/business/companies/3614102-Microsoft-prekraschaet-podderzhku-Internet-Explorer)
<pre>
.designed {
    float: right;
    display: block;
    margin-top: 54px;
    font-size: 11.5px;
    font-weight: 500px;-ошибка
    font-family: 'Open Sans';
    color: white;
}
</pre>

http://joxi.ru/LmGD9PEuRpyNp2 - подправь
http://joxi.ru/5mdMgP7ivKxde2 - смести

**Comment by maxhasl** [comment]
UPDATED!!!

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
